### ISSUE TITLE
How can one be part of DataKind-BLR?

### ISSUE THREAD

**Issue by amrrs** [DataKind-BLR/OpenCity-Sprint-2018#1]
Hey,

How can one be part of DataKind-BLR to contribute?

**Comment by raghuramdr** [comment]
Hi @amrrs, thank you for your interest in DataKind Bangalore. Please join our [Meetup](https://www.meetup.com/DataKind-Bangalore/) and join our [Slack channel](https://dkblr-slack.herokuapp.com/) to be in the know about our latest Meetups and announcements. In fact, we have a Meetup this coming Sunday. Looking forward to your contribution!!

Hope I have answered your question

**Comment by amrrs** [comment]
Thanks @raghuramdr  Will check that!

**Comment by raghuramdr** [comment]
Cool!! Expect to see you at our upcoming Meetup @amrrs
