### ISSUE TITLE
Evaluate Plotly

### ISSUE THREAD

**Issue by Deepthi-Chand** [DataKind-BLR/OpenCity-Sprint-2018#4]

**Comment by punchagan** [comment]
We could also look at [Dash](https://plot.ly/products/dash/)

**Comment by azure31** [comment]
Plotly is fully open-source and can be used to make interactive graphs. Dash which is built on top of plotly can be used to make dashboards that can be easily hosted locally or on a web server. No javascript required. This link explains the basics of [dash](https://medium.com/@plotlygraphs/introducing-dash-5ecf7191b503).

Tutorial available [here](https://dash.plot.ly/)

These example apps could be useful for our use case: [here](https://opioid-epidemic.herokuapp.com/) and [here](https://opioid-epidemic.herokuapp.com/)

**Comment by Deepthi-Chand** [comment]
@punchagan @azure31 Can either of you take one of the datasets and bring up a simple analysis page with some map component in it. I will try and do the same for superset. This might give a better idea of what we can go with.

**Comment by azure31** [comment]
It seems plotly is not ideal to make city-level plots as mentioned in: https://github.com/plotly/plotly.js/issues/249

They recommend using leaflet instead.

**Comment by raghuramdr** [comment]
Enterprise version
