### ISSUE TITLE
Scrape polling stations for Bangalore district

### ISSUE THREAD

**Issue by fx86** [DataKind-BLR/OpenCity-Sprint-2018#9]
Write a python script to download the polling station details and then geocode them.

source of data - http://psleci.nic.in

**Comment by thejeshgn** [comment]
Some discussions here

https://groups.google.com/forum/#!topic/datameet/IvMePblFEk8

**Comment by fx86** [comment]
Too late :), ran this yesterday https://github.com/DataKind-BLR/OpenCity-Sprint-2018/commit/717f05afc2071c253278498745c044b707565365

Got 700 stations, will keep it humming for 2 more days and upload the data.

**Comment by fx86** [comment]
Scraper still on-going. Results till now, are stored here- https://drive.google.com/open?id=1ZmO_f8lfPvAi8w0LTkXXLT9I7WT9czZr
